#!/usr/bin/env node
/**
 * Regenerates src/index.ts (the barrel file) and src/icon-catalog.json
 * (used by the Storybook "Icons" story) from whatever .tsx files currently
 * exist in src/icons/. Run after every Figma export so neither file is
 * ever hand-maintained.
 */
const fs = require('node:fs');
const path = require('node:path');
const fg = require('fast-glob');

const SRC_DIR = path.resolve(__dirname, '../src');
const ICONS_DIR = path.join(SRC_DIR, 'icons');

function main() {
  const files = fg.sync('*.tsx', { cwd: ICONS_DIR }).sort();

  const entries = files.map((file) => {
    const source = fs.readFileSync(path.join(ICONS_DIR, file), 'utf8');
    const match = source.match(/export function (Icon\w+)/);
    if (!match) {
      throw new Error(`${file}: no exported "Icon*" component found.`);
    }
    return { file, componentName: match[1] };
  });

  const barrel = [
    '/* AUTO-GENERATED by scripts/build-catalog.cjs — do not edit by hand. */',
    "export type { IconProps } from './Icon';",
    ...entries.map(
      ({ file, componentName }) =>
        `export { ${componentName} } from './icons/${file.replace(/\.tsx$/, '')}';`,
    ),
    '',
  ].join('\n');

  fs.writeFileSync(path.join(SRC_DIR, 'index.ts'), barrel);

  const catalog = entries.map(({ componentName }) => ({
    name: componentName,
    exportName: componentName,
  }));
  fs.writeFileSync(
    path.join(SRC_DIR, 'icon-catalog.json'),
    JSON.stringify(catalog, null, 2) + '\n',
  );

  console.log(`Regenerated index.ts and icon-catalog.json for ${entries.length} icon(s).`);
}

main();
