/* AUTO-GENERATED by scripts/build-catalog.cjs — do not edit by hand. */
export type { IconProps } from './Icon';
export { IconArrowRight } from './icons/ArrowRight';
export { IconCheck } from './icons/Check';
export { IconClose } from './icons/Close';
export { IconDelete } from './icons/Delete';
export { IconFemale } from './icons/Female';
export { IconHospital } from './icons/Hospital';
export { IconMale } from './icons/Male';
export { IconMenu } from './icons/Menu';
export { IconSearch } from './icons/Search';
export { IconUserAdd } from './icons/UserAdd';
export { IconUsertag } from './icons/Usertag';
